M48
; DRILL file {KiCad 7.0.7} date Sun Aug 27 17:08:43 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-27T17:08:43+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X51.83Y-71.61
X51.84Y-132.71
X186.99Y-86.55
X187.0Y-121.46
T2
X95.375Y-104.125
T0
M30
